---
- hosts: server_deploy
  become: yes
  tasks:
     - name: Copy file buil to remote
       ansible.builtin.copy:
         src: 
         dest:
         owner: root
         group: root
         mode: '755' 